---
- name: Optimize Deployment
  hosts: all
  gather_facts: yes
  become: true
  remote_user: ubuntu
  roles:
    - docker
    - docker-dependancies

  tasks:
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
        enabled: yes
      async: 300
      poll: 0

    - name: Wait for nginx to be installed
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: async_results
      until: async_results.finished
      retries: 30
      delay: 10
      with_items:
        - "{{ ansible_job_ids }}"
      when: async_results.ansible_job_id is defined

    - name: Copy configuration file
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx
      become: yes

    - name: Ensure nginx container is running
      docker_container:
        name: my_nginx
        image: nginx:latest
        state: started
        ports:
          - "8080:80"
        # volumes:
        #   - /var/:/usr/share/nginx/html
      

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      become: yes

