replicaCount: 1

image:
  repository: daradesudarshan/centralrepo
  tag: nginx-frontend-v5
  pullPolicy: IfNotPresent

service:
  name: frontend-service
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  name: ""
  nginx_class: ""
  path: /
  pathType: ImplementationSpecific
  hosts:
  - host: chart-example.local
    paths:
    - /
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
