pipeline {
    environment {
        imagename = "daradesudarshan/centralrepo"
        dockerImage = ''
        containerName = 'capstone-webapp-v1'
        dockerHubCredentials = 'docker'
        kubernetes_server_private_ip="10.0.1.178"
        //ansible_server_private_ip="localhost"
        //KUBECONFIG_CREDENTIALS_ID = 'minikube-config' // Update with your Kubeconfig credentials ID
        MY_KUBECONFIG = credentials('minikube-config')
    }

    agent any
 
    stages {
        stage('Cloning Git') {
            steps {
                git([url:'https://github.com/darade-sudarshan/fruitables-Ecommerce.git', branch: 'main'])
            }
        }
        stage('Building image') {
            steps {
                script {
                     dir('frontend') {
                        dockerImage = docker.build "${imagename}:${containerName}"
                     }
                }
            }
        }
 
        stage('Running image') {
            steps {
                script {
                    sh "docker run -dit --name ${containerName} ${imagename}:${containerName} /bin/bash"
                    // Perform any additional steps needed while the container is running
                }
            }
        }
 
        stage('Stop and Remove Container') {
            steps {
                script {
                    sh "docker stop ${containerName} || true"
                    sh "docker rm ${containerName} || true"
                }
            }
        }
 
        stage('Deploy Image') {
            steps {
                script {
                    // Use Jenkins credentials for Docker Hub login
                    withCredentials([usernamePassword(credentialsId: dockerHubCredentials, usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
 
                        // Push the image
                        sh "docker push ${imagename}:${containerName}"
                    }
                }
            }
        }
        stage('Cleaning up') { 
            steps { 
                sh "docker rmi ${imagename}:${containerName}" 
            }
        }
        stage('Test Kubernetes connectivity') {
            steps {
                sh("kubectl get pods -n production --kubeconfig $MY_KUBECONFIG")
            }
        }
    }
}
