---
- name: Manage files on managed nodes
  hosts: all
  become: yes
  tasks:

    - name: Ensure a file is present
      ansible.builtin.file:
        path: /home/ubuntu/file.txt
        state: touch

    - name: Create a file with specific content
      ansible.builtin.copy:
        dest: /home/ubuntu/file_with_content.txt
        content: "This is the content of the file.\n"

    - name: Delete a file
      ansible.builtin.file:
        path: /home/ubuntu/abc.txt
        state: absent

    - name: Modify a file by appending a line
      ansible.builtin.lineinfile:
        path: /home/ubuntu/file_with_content.txt
        line: "New line to be added to the file."

    - name: Ensure a directory is present
      ansible.builtin.file:
        path: /home/ubuntu/.ssh
        state: directory

    - name: Delete a directory
      ansible.builtin.file:
        path: /home/ubuntu/abc
        state: absent

    - name: Set permissions on a file
      ansible.builtin.file:
        path: /home/ubuntu/file.txt
        mode: '0644'

    - name: Set ownership on a file
      ansible.builtin.file:
        path: /home/ubuntu/file.txt
        owner: ubuntu
        group: admin
