---
- hosts: all
  become: yes
  vars:
    mysql_root_password: "my_root_password" # modify password for your root database account
    mysql_db_name: "database"
    mysql_user: "appuser"
    mysql_user_password: "my_password" # modify password for your database
    backup_dir: "/srv/backups/mysql"
    cron_time: "0 2 * * *"  # Daily at 2 AM

  tasks:
    - name: Installing Mysql  and dependencies
      package:
       name: "{{item}}"
       state: present
       update_cache: yes
      loop:
       - mysql-server
       - mysql-client 
       - python3-mysqldb
       - libmysqlclient-dev


    - name: start and enable mysql service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Set MySQL root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        host_all: yes
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Remove anonymous MySQL user
      mysql_user:
        name: ''
        host: localhost
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Remove MySQL test database
      mysql_db:
        name: test
        state: absent
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL database
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Create MySQL user
      mysql_user:
        name: "{{ mysql_user }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_db_name }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"

    - name: Install cron package
      apt:
        name: cron
        state: present

    - name: Ensure cron is running
      service:
        name: cron
        state: started
        enabled: yes

    - name: Create backup directory
      file:
        path: "{{ backup_dir }}"
        state: directory
        mode: '0755'

    - name: Create backup script
      copy:
        content: |
          #!/bin/bash
          mysqldump -u {{ mysql_user }} -p{{ mysql_user_password }} {{ mysql_db_name }} > {{ backup_dir }}/backup_$(date +\%F).sql
        dest: /usr/local/bin/mysql_backup.sh
        mode: '0755'

    - name: Set up cron job for database backup
      cron:
        name: "MySQL Backup"
        minute: "{{ cron_time.split()[0] }}"
        hour: "{{ cron_time.split()[1] }}"
        day: "{{ cron_time.split()[2] }}"
        month: "{{ cron_time.split()[3] }}"
        weekday: "{{ cron_time.split()[4] }}"
        job: "/usr/local/bin/mysql_backup.sh"
