apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default # Change this to the service account or user you want to grant permissions to
    namespace: default # Change this to the namespace of the service account
roleRef:
  kind: ClusterRole
  name: helm-clusterrole
  apiGroup: rbac.authorization.k8s.io
